[package]
name = "tori"
description = "The frictionless music player for the terminal"
author = "Leonardo Riether <riether.leonardo@gmail.com>"
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://github.com/LeoRiether/tori"
keywords = ["music", "player", "tui", "terminal"]
exclude = ["/assets"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# https://github.com/flamegraph-rs/flamegraph#cargo-flamegraph
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]

[dependencies]
tui = "0.19"
crossterm = "0.25"

# libmpv isn't working for mpv v0.35 :(
# So I'm using a fork :)
# The changes have already been pulled though, so I should be able to switch back soon
# https://github.com/ParadoxSpiral/libmpv-rs/pull/28
libmpv-sirno = "2.0.2-fork.1"

clipboard = "0.5.0"
serde_json = "1.0.94"
unicode-width = "0.1.10"
dirs = "5.0.0"
serde_yaml = "0.9.19"
webbrowser = "0.8.8"
serde = { version = "1.0.159", features = ["derive"] }
once_cell = "1.17.1"
argh = "0.1.10"
lofty = "0.11.0"
rand = "0.8.5"
