playlists_dir: this is a placeholder value, src/config.rs overrides it
visualizer_gradient:
  - "#2e1442"
  - "#101e47"
keybindings:
  '?': OpenHelpModal
  C-c: Quit
  C-d: Quit
  q: Quit
  ">": NextSong
  "<": PrevSong
  " ": TogglePause
  L: ToggleLoop
  S-right: SeekForward
  S-left: SeekBackward
  o: OpenInBrowser
  y: CopyUrl
  t: CopyTitle
  A-up: VolumeUp
  A-down: VolumeDown
  m: Mute
  v: ToggleVisualizer
  s: NextSortingMode
  R: Rename
  X: Delete
  S-down: SwapSongDown
  S-up: SwapSongUp
  J: SwapSongDown
  K: SwapSongUp
  ",": Shuffle
  h: SelectLeft
  j: SelectNext
  k: SelectPrev
  l: SelectRight
  left: SelectLeft
  down: SelectNext
  up: SelectPrev
  right: SelectRight
  a: Add
  u: QueueSong
  C-q: QueueShown
  p: PlayFromModal
  E: OpenInEditor
  '!': OpenHotkeyModal 
  C-f: Search
  g: GotoStart
  G: GotoEnd
