name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt-get update
      run: sudo apt-get update
    - name: Install libmpv
      run: sudo apt-get -y install libmpv-dev libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  windows-build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - run: choco install mpvio
    - name: Build mpv.lib
      run: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat" x64
    - run: lib /def:mpv.def /name:mpv-1.dll /out:mpv.lib /MACHINE:X64
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
